"""
Module 1: Data Ingestion - AI Story Generator
=============================================
Tạo truyện hư cấu 100% bằng AI (OpenAI GPT-4o / Claude).
KHÔNG cào truyện có bản quyền từ Internet.

Usage:
    from module_1_ingestion import StoryGenerator

    gen = StoryGenerator(api_key="sk-...")
    story = gen.generate_story(genre="ngon_tinh_hien_dai", num_chapters=6)
    gen.save_story(story, "data/stories/")
"""

import hashlib
import json
import os
import random
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from loguru import logger

# Attempt imports - gracefully degrade if not installed
try:
    import openai
    HAS_OPENAI = True
except ImportError:
    HAS_OPENAI = False
    logger.warning("openai package not installed. Install with: pip install openai")

try:
    import anthropic
    HAS_ANTHROPIC = True
except ImportError:
    HAS_ANTHROPIC = False
    logger.warning("anthropic package not installed. Install with: pip install anthropic")


# ============================================================
# Genre Definitions
# ============================================================
GENRES = {
    "ngon_tinh_hien_dai": {
        "name_vi": "Ngôn Tình Hiện Đại",
        "name_en": "Modern Romance",
        "keywords": "tình yêu, hiện đại, thành phố, công sở, thanh xuân",
        "typical_tropes": "hợp đồng tình yêu, fake dating, enemies to lovers, tổng tài yêu thầm",
        "target_audience": "Nữ 18-35",
        "mood": "ngọt ngào, lãng mạn, có drama nhẹ",
    },
    "ngon_tinh_tong_tai": {
        "name_vi": "Ngôn Tình Tổng Tài",
        "name_en": "CEO Romance",
        "keywords": "tổng tài, bá đạo, sủng vợ, hào môn, giàu có, quyền lực",
        "typical_tropes": "tổng tài lạnh lùng, cô gái nghèo, hôn nhân hợp đồng, sủng lên trời",
        "target_audience": "Nữ 20-40",
        "mood": "kịch tính, sủng ngọt, bá đạo",
    },
    "trong_sinh_xuyen_khong": {
        "name_vi": "Trọng Sinh / Xuyên Không",
        "name_en": "Rebirth / Time Travel",
        "keywords": "trọng sinh, xuyên không, sống lại, quá khứ, cổ đại, báo thù",
        "typical_tropes": "sống lại kiếp trước, biết trước tương lai, quay về báo thù, làm lại cuộc đời",
        "target_audience": "Nữ 20-35",
        "mood": "kịch tính, hồi hộp, thỏa mãn",
    },
    "co_dai_cung_dau": {
        "name_vi": "Cổ Đại / Cung Đấu",
        "name_en": "Ancient / Palace Intrigue",
        "keywords": "cổ đại, cung đấu, vương phi, hoàng đế, triều đình, quyền mưu",
        "typical_tropes": "phi tần tranh sủng, thân phận thấp vươn lên, hoàng đế sủng phi, mưu kế cung đình",
        "target_audience": "Nữ 22-45",
        "mood": "trang trọng, kịch tính, gay cấn",
    },
    "thanh_xuan_vuon_truong": {
        "name_vi": "Thanh Xuân Vườn Trường",
        "name_en": "School Life / Youth",
        "keywords": "học đường, thanh xuân, học sinh, tình đầu, trong sáng",
        "typical_tropes": "yêu thầm bạn cùng bàn, học bá và học tra, thanh mai trúc mã, từ trường ra đời",
        "target_audience": "Nữ 16-28",
        "mood": "trong sáng, ngọt ngào, hoài niệm",
    },
    "chua_lanh_gia_dinh": {
        "name_vi": "Chữa Lành / Gia Đình",
        "name_en": "Healing / Family",
        "keywords": "chữa lành, gia đình, tổn thương, hàn gắn, yêu thương, tích cực",
        "typical_tropes": "tổn thương tuổi thơ, tìm lại gia đình, tha thứ, xây dựng tổ ấm",
        "target_audience": "Nữ 25-50",
        "mood": "ấm áp, cảm động, tích cực, nhẹ nhàng",
    },
    "nu_cuong": {
        "name_vi": "Nữ Cường",
        "name_en": "Strong Female Lead",
        "keywords": "nữ cường, độc lập, mạnh mẽ, kinh doanh, tự chủ, thành đạt",
        "typical_tropes": "nữ chính tự lập, không phụ thuộc đàn ông, xây dựng sự nghiệp, vả mặt trà xanh",
        "target_audience": "Nữ 22-40",
        "mood": "mạnh mẽ, truyền cảm hứng, thỏa mãn",
    },
    "hai_huoc_doi_thuong": {
        "name_vi": "Hài Hước Đời Thường",
        "name_en": "Comedy / Slice of Life",
        "keywords": "hài hước, đời thường, gia đình, công sở, hóm hỉnh, giải trí",
        "typical_tropes": "tình huống dở khóc dở cười, hiểu lầm vui nhộn, nhân vật lầy lội, happy ending",
        "target_audience": "Tất cả 18-45",
        "mood": "vui nhộn, thư giãn, tích cực",
    },
}

# Disclaimer template - BẮT BUỘC cho mọi truyện
DISCLAIMER_VI = (
    "Đây là câu chuyện HOÀN TOÀN HƯ CẤU được tạo ra bởi AI. "
    "Mọi nhân vật, sự kiện, địa danh, tổ chức trong truyện đều là sản phẩm "
    "của trí tưởng tượng và không liên quan đến bất kỳ người thật hay "
    "sự kiện thực tế nào. Truyện được sản xuất nhằm mục đích giải trí."
)

DISCLAIMER_EN = (
    "This is a COMPLETELY FICTIONAL story generated by AI. "
    "All characters, events, locations, and organizations are products "
    "of imagination and do not represent real people or actual events. "
    "This story is produced for entertainment purposes only."
)


# ============================================================
# Story Generator Class
# ============================================================
class StoryGenerator:
    """
    Generate original Vietnamese fictional stories using AI APIs.

    Supports: OpenAI GPT-4o, Anthropic Claude, Google Gemini
    All stories are 100% fictional and original.
    """

    def __init__(
        self,
        openai_api_key: Optional[str] = None,
        anthropic_api_key: Optional[str] = None,
        engine: str = "openai",
        model: Optional[str] = None,
        output_dir: str = "data/stories",
    ):
        """
        Initialize Story Generator.

        Args:
            openai_api_key: OpenAI API key
            anthropic_api_key: Anthropic API key
            engine: AI engine to use ("openai", "anthropic", or "gemini")
            model: Model name override (defaults to best available)
            output_dir: Directory to save generated stories
        """
        self.engine = engine.lower()
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Set default models
        if model is None:
            model_map = {
                "openai": "gpt-4o",
                "anthropic": "claude-sonnet-4-6",
                "gemini": "gemini-2.5-pro",
            }
            model = model_map.get(self.engine, "gpt-4o")
        self.model = model

        # Initialize clients
        self.openai_client = None
        self.anthropic_client = None

        if self.engine == "openai":
            api_key = openai_api_key or os.getenv("OPENAI_API_KEY")
            if not api_key:
                raise ValueError("OpenAI API key required. Set OPENAI_API_KEY env var.")
            if HAS_OPENAI:
                self.openai_client = openai.OpenAI(api_key=api_key)
            else:
                raise ImportError("openai package required: pip install openai")

        elif self.engine == "anthropic":
            api_key = anthropic_api_key or os.getenv("ANTHROPIC_API_KEY")
            if not api_key:
                raise ValueError("Anthropic API key required. Set ANTHROPIC_API_KEY env var.")
            if HAS_ANTHROPIC:
                self.anthropic_client = anthropic.Anthropic(api_key=api_key)
            else:
                raise ImportError("anthropic package required: pip install anthropic")

        logger.info(f"StoryGenerator initialized with engine={self.engine}, model={self.model}")

    # ============================================================
    # Main Generation Method
    # ============================================================
    def generate_story(
        self,
        genre: str = "ngon_tinh_hien_dai",
        num_chapters: int = 6,
        words_per_chapter: int = 1500,
        title: Optional[str] = None,
        extra_instructions: Optional[str] = None,
    ) -> Dict:
        """
        Generate a complete original fictional story.

        Args:
            genre: Story genre (key from GENRES dict)
            num_chapters: Number of chapters (2-10)
            words_per_chapter: Target words per chapter (1000-3000)
            title: Optional custom title. If None, AI will create one.
            extra_instructions: Additional instructions for the AI

        Returns:
            Dictionary with story metadata and chapters
        """
        if genre not in GENRES:
            raise ValueError(f"Unknown genre '{genre}'. Available: {list(GENRES.keys())}")

        genre_info = GENRES[genre]
        story_id = hashlib.md5(
            f"{genre}_{datetime.now().isoformat()}".encode()
        ).hexdigest()[:12]

        logger.info(
            f"Generating story: id={story_id}, genre={genre}, "
            f"chapters={num_chapters}, words/ch={words_per_chapter}"
        )

        # Generate title if not provided
        if title is None:
            title = self._generate_title(genre_info, num_chapters)

        # Generate each chapter
        chapters = []
        story_context = ""  # Accumulated context for continuity

        for ch_num in range(1, num_chapters + 1):
            logger.info(f"  Generating chapter {ch_num}/{num_chapters}...")

            chapter = self._generate_chapter(
                genre_info=genre_info,
                chapter_num=ch_num,
                total_chapters=num_chapters,
                target_words=words_per_chapter,
                story_title=title,
                context=story_context,
                extra_instructions=extra_instructions,
            )

            chapter_data = {
                "chapter": ch_num,
                "title": chapter.get("title", f"Chương {ch_num}"),
                "text": chapter["text"],
                "word_count": len(chapter["text"].split()),
            }
            chapters.append(chapter_data)

            # Update context for next chapter (keep last ~1000 chars)
            story_context += f"\n--- Chương {ch_num} ---\n{chapter['text'][-1000:]}\n"
            logger.info(f"    Chapter {ch_num}: {chapter_data['word_count']} words")

        # Assemble story
        story = {
            "id": story_id,
            "title": title,
            "genre": genre,
            "genre_name_vi": genre_info["name_vi"],
            "mood": genre_info["mood"],
            "created_at": datetime.now().isoformat(),
            "engine": self.engine,
            "model": self.model,
            "total_chapters": num_chapters,
            "total_words": sum(ch["word_count"] for ch in chapters),
            "chapters": chapters,
            "disclaimer_vi": DISCLAIMER_VI,
            "disclaimer_en": DISCLAIMER_EN,
            "is_fictional": True,
            "is_ai_generated": True,
        }

        logger.info(
            f"Story complete: '{title}' - {num_chapters} chapters, "
            f"{story['total_words']} total words"
        )
        return story

    # ============================================================
    # Chapter Generation
    # ============================================================
    def _generate_chapter(
        self,
        genre_info: Dict,
        chapter_num: int,
        total_chapters: int,
        target_words: int,
        story_title: str,
        context: str,
        extra_instructions: Optional[str] = None,
    ) -> Dict:
        """Generate a single chapter using the AI engine."""
        # Build chapter position instruction
        if chapter_num == 1:
            position_guide = (
                "Đây là CHƯƠNG MỞ ĐẦU. Giới thiệu nhân vật chính, bối cảnh, "
                "và tình huống ban đầu. Kết thúc chương bằng một tình tiết "
                "khiến người đọc tò mò muốn đọc tiếp."
            )
        elif chapter_num == total_chapters:
            position_guide = (
                "Đây là CHƯƠNG CUỐI CÙNG. Giải quyết các nút thắt, hoàn thiện "
                "câu chuyện với một cái kết trọn vẹn và ý nghĩa. "
                "Kết thúc có hậu (HE - Happy Ending)."
            )
        else:
            position_guide = (
                f"Đây là CHƯƠNG {chapter_num}/{total_chapters}. "
                "Phát triển cốt truyện, thêm tình tiết mới, xây dựng cao trào. "
                "Kết thúc chương ở một điểm gay cấn hoặc thú vị."
            )

        system_prompt = (
            "Bạn là một nhà văn chuyên viết truyện ngôn tình tiếng Việt với "
            "hơn 10 năm kinh nghiệm. Bạn viết truyện HOÀN TOÀN HƯ CẤU, "
            "không dựa trên bất kỳ người thật hay sự kiện thật nào.\n\n"
            "QUY TẮC BẮT BUỘC:\n"
            "- Tất cả tên nhân vật, địa danh, tổ chức đều PHẢI là sản phẩm tưởng tượng\n"
            "- KHÔNG được dùng tên người thật, địa danh thật, công ty thật\n"
            "- Viết bằng TIẾNG VIỆT tự nhiên, giàu cảm xúc\n"
            "- Văn phong phù hợp để ĐỌC THÀNH AUDIO (câu văn xuôi, dễ nghe)\n"
            "- Không dùng từ ngữ phản cảm, chính trị, tôn giáo\n"
            "- Dialog (hội thoại) nên rõ ràng, phân biệt được người nói\n"
            "- Kết hợp miêu tả cảm xúc và hành động hợp lý"
        )

        user_prompt = (
            f"VIẾT MỘT CHƯƠNG TRUYỆN với các thông số sau:\n\n"
            f"TIÊU ĐỀ TRUYỆN: {story_title}\n"
            f"THỂ LOẠI: {genre_info['name_vi']} ({genre_info['keywords']})\n"
            f"KHÔNG KHÍ: {genre_info['mood']}\n"
            f"ĐỐI TƯỢNG ĐỘC GIẢ: {genre_info['target_audience']}\n"
            f"CHƯƠNG: {chapter_num}/{total_chapters}\n"
            f"ĐỘ DÀI MỤC TIÊU: Khoảng {target_words} từ\n"
            f"HƯỚNG DẪN: {position_guide}\n"
            f"MOTIF GỢI Ý: {genre_info['typical_tropes']}\n\n"
            f"BỐI CẢNH TRUYỆN ĐẾN HIỆN TẠI:\n{context if context else '(Chưa có - đây là chương đầu tiên)'}\n\n"
        )

        if extra_instructions:
            user_prompt += f"YÊU CẦU BỔ SUNG:\n{extra_instructions}\n\n"

        user_prompt += (
            "QUAN TRỌNG:\n"
            "- Xuất ra TIẾNG VIỆT thuần túy (không pha tiếng Anh)\n"
            "- Kết thúc chương bằng dấu hiệu rõ ràng\n"
            "- Định dạng: Tiêu đề chương → Nội dung\n"
            "- Có thể thêm tiêu đề phụ cho chương này (ví dụ: 'Chương 1: Gặp Gỡ Định Mệnh')"
        )

        # Call AI engine
        if self.engine == "openai":
            chapter_text = self._call_openai(system_prompt, user_prompt, target_words)
        elif self.engine == "anthropic":
            chapter_text = self._call_anthropic(system_prompt, user_prompt, target_words)
        else:
            raise ValueError(f"Unknown engine: {self.engine}")

        # Parse chapter title from first line if present
        lines = chapter_text.strip().split("\n")
        chapter_title = f"Chương {chapter_num}"
        if lines and ("Chương" in lines[0] or "chương" in lines[0].lower()):
            chapter_title = lines[0].strip().lstrip("#").strip()
            chapter_text = "\n".join(lines[1:]).strip()

        return {"title": chapter_title, "text": chapter_text}

    # ============================================================
    # AI API Calls
    # ============================================================
    def _call_openai(self, system_prompt: str, user_prompt: str, target_words: int) -> str:
        """Call OpenAI API to generate a chapter."""
        max_tokens = target_words * 3  # Rough estimate for Vietnamese

        response = self.openai_client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.9,
            max_tokens=min(max_tokens, 16000),
            top_p=0.95,
            frequency_penalty=0.3,
            presence_penalty=0.3,
        )
        return response.choices[0].message.content

    def _call_anthropic(self, system_prompt: str, user_prompt: str, target_words: int) -> str:
        """Call Anthropic Claude API to generate a chapter."""
        max_tokens = target_words * 3

        response = self.anthropic_client.messages.create(
            model=self.model,
            system=system_prompt,
            messages=[{"role": "user", "content": user_prompt}],
            temperature=0.9,
            max_tokens=min(max_tokens, 16000),
        )
        return response.content[0].text

    # ============================================================
    # Title Generation
    # ============================================================
    def _generate_title(self, genre_info: Dict, num_chapters: int) -> str:
        """Generate an engaging Vietnamese story title."""
        title_prompt = (
            f"Tạo MỘT tiêu đề truyện ngôn tình tiếng Việt, thể loại {genre_info['name_vi']}. "
            f"Tiêu đề phải:\n"
            f"- HOÀN TOÀN HƯ CẤU (không trùng với truyện có thật)\n"
            f"- Bằng tiếng Việt, viết IN HOA\n"
            f"- Hấp dẫn, gợi tò mò, phù hợp với thể loại {genre_info['keywords']}\n"
            f"- Độ dài 8-15 từ\n"
            f"- Phong cách giống truyện ngôn tình Trung Quốc dịch sang tiếng Việt\n"
            f"Chỉ trả về TIÊU ĐỀ, không kèm giải thích."
        )

        if self.engine == "openai":
            response = self.openai_client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": title_prompt}],
                temperature=0.95,
                max_tokens=100,
            )
            title = response.choices[0].message.content.strip()
        elif self.engine == "anthropic":
            response = self.anthropic_client.messages.create(
                model=self.model,
                messages=[{"role": "user", "content": title_prompt}],
                temperature=0.95,
                max_tokens=100,
            )
            title = response.content[0].text.strip()

        # Clean up title
        title = title.strip('"').strip("'").strip()
        # Remove common prefixes that AI might add
        for prefix in ["Tiêu đề:", "Title:", "Tên truyện:"]:
            if title.lower().startswith(prefix.lower()):
                title = title[len(prefix):].strip()
        return title.upper()

    # ============================================================
    # Batch Generation
    # ============================================================
    def generate_batch(
        self,
        count: int = 5,
        genres: Optional[List[str]] = None,
        num_chapters: int = 6,
        words_per_chapter: int = 1500,
    ) -> List[Dict]:
        """
        Generate multiple stories.

        Args:
            count: Number of stories to generate
            genres: List of genres (randomly chosen if None)
            num_chapters: Chapters per story
            words_per_chapter: Words per chapter
        """
        stories = []
        for i in range(count):
            genre = random.choice(genres) if genres else random.choice(list(GENRES.keys()))
            logger.info(f"Batch story {i+1}/{count}: genre={genre}")

            try:
                story = self.generate_story(
                    genre=genre,
                    num_chapters=num_chapters,
                    words_per_chapter=words_per_chapter,
                )
                self.save_story(story)
                stories.append(story)
            except Exception as e:
                logger.error(f"Failed to generate story {i+1}: {e}")
                continue

        logger.info(f"Batch complete: {len(stories)}/{count} stories generated")
        return stories

    # ============================================================
    # Save & Load
    # ============================================================
    def save_story(self, story: Dict, output_dir: Optional[str] = None) -> str:
        """Save story to JSON file."""
        output_dir = Path(output_dir or self.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        filename = f"{story['id']}_{story['genre']}.json"
        filepath = output_dir / filename

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(story, f, ensure_ascii=False, indent=2)

        logger.info(f"Story saved: {filepath}")
        return str(filepath)

    @staticmethod
    def load_story(filepath: str) -> Dict:
        """Load a story from JSON file."""
        with open(filepath, "r", encoding="utf-8") as f:
            return json.load(f)

    @staticmethod
    def list_stories(stories_dir: str = "data/stories") -> List[Dict]:
        """List all generated stories with metadata."""
        stories_dir = Path(stories_dir)
        stories = []

        for json_file in sorted(stories_dir.glob("*.json")):
            with open(json_file, "r", encoding="utf-8") as f:
                story = json.load(f)
            stories.append({
                "id": story.get("id", ""),
                "title": story.get("title", ""),
                "genre": story.get("genre", ""),
                "genre_name_vi": story.get("genre_name_vi", ""),
                "chapters": story.get("total_chapters", 0),
                "total_words": story.get("total_words", 0),
                "created_at": story.get("created_at", ""),
                "file": str(json_file),
            })

        return stories


# ============================================================
# CLI Entry Point
# ============================================================
def main():
    """CLI interface for story generation."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate original fictional stories using AI"
    )
    parser.add_argument(
        "--genre", type=str, default="ngon_tinh_hien_dai",
        choices=list(GENRES.keys()),
        help="Story genre"
    )
    parser.add_argument(
        "--chapters", type=int, default=6,
        help="Number of chapters (2-10)"
    )
    parser.add_argument(
        "--words", type=int, default=1500,
        help="Words per chapter"
    )
    parser.add_argument(
        "--batch", type=int, default=1,
        help="Generate multiple stories at once"
    )
    parser.add_argument(
        "--engine", type=str, default="openai",
        choices=["openai", "anthropic"],
        help="AI engine to use"
    )
    parser.add_argument(
        "--output", type=str, default="data/stories",
        help="Output directory"
    )
    parser.add_argument(
        "--title", type=str, default=None,
        help="Custom story title"
    )
    parser.add_argument(
        "--list", action="store_true",
        help="List all generated stories"
    )

    args = parser.parse_args()

    if args.list:
        stories = StoryGenerator.list_stories(args.output)
        if not stories:
            print("No stories found.")
            return
        print(f"\n{'ID':<14} {'Title':<50} {'Genre':<25} {'Ch':<5} {'Words':<8}")
        print("-" * 105)
        for s in stories:
            print(
                f"{s['id']:<14} {s['title'][:48]:<50} "
                f"{s['genre_name_vi'][:23]:<25} {s['chapters']:<5} "
                f"{s['total_words']:<8}"
            )
        return

    # Initialize generator
    gen = StoryGenerator(engine=args.engine, output_dir=args.output)

    if args.batch > 1:
        stories = gen.generate_batch(
            count=args.batch,
            genres=[args.genre],
            num_chapters=args.chapters,
            words_per_chapter=args.words,
        )
        for s in stories:
            print(f"  ✓ {s['id']}: {s['title']} ({s['total_words']} words)")
    else:
        story = gen.generate_story(
            genre=args.genre,
            num_chapters=args.chapters,
            words_per_chapter=args.words,
            title=args.title,
        )
        gen.save_story(story)
        print(f"\n✓ Story generated: {story['title']}")
        print(f"  ID: {story['id']}")
        print(f"  Genre: {story['genre_name_vi']}")
        print(f"  Chapters: {story['total_chapters']}")
        print(f"  Total words: {story['total_words']}")


if __name__ == "__main__":
    main()
